/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                mousse: {
                    DEFAULT: '#2E4036',
                    50: '#f4f6f5',
                    100: '#e0e6e2',
                    200: '#c1cec6',
                    300: '#99ada2',
                    400: '#728a7d',
                    500: '#577063',
                    600: '#445a4f',
                    700: '#2E4036',
                    800: '#2a3a31',
                    900: '#24312a',
                    950: '#141c17',
                },
                argile: {
                    DEFAULT: '#CC5833',
                    50: '#fdf5f1',
                    100: '#fbe8de',
                    200: '#f6cdbd',
                    300: '#f0aa92',
                    400: '#e67d5a',
                    500: '#CC5833',
                    600: '#c44a28',
                    700: '#a33a22',
                    800: '#843221',
                    900: '#6c2c1f',
                    950: '#3a140d',
                },
                creme: {
                    DEFAULT: '#F2F0E9',
                    50: '#FAFAF8',
                    100: '#F2F0E9',
                    200: '#E8E4D9',
                    300: '#D6D0BF',
                    400: '#C1B8A1',
                    500: '#AFA48A',
                },
                charbon: {
                    DEFAULT: '#1A1A1A',
                    50: '#f5f5f5',
                    100: '#e5e5e5',
                    200: '#cccccc',
                    300: '#a3a3a3',
                    400: '#737373',
                    500: '#525252',
                    600: '#3d3d3d',
                    700: '#2e2e2e',
                    800: '#1A1A1A',
                    900: '#141414',
                    950: '#0a0a0a',
                },
            },
            fontFamily: {
                display: ['"Plus Jakarta Sans"', 'sans-serif'],
                heading: ['"Outfit"', 'sans-serif'],
                dramatic: ['"Cormorant Garamond"', 'serif'],
                mono: ['"IBM Plex Mono"', 'monospace'],
                body: ['"Plus Jakarta Sans"', 'sans-serif'],
            },
            borderRadius: {
                '2xl': '1rem',
                '3xl': '1.5rem',
                '4xl': '2rem',
                '5xl': '3rem',
            },
            animation: {
                'float': 'float 6s ease-in-out infinite',
                'pulse-slow': 'pulse 4s ease-in-out infinite',
                'pulse-dot': 'pulseDot 2s ease-in-out infinite',
                'orb-float': 'orbFloat 8s ease-in-out infinite',
                'typewriter-cursor': 'blink 1s step-end infinite',
            },
            keyframes: {
                float: {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-12px)' },
                },
                orbFloat: {
                    '0%, 100%': { transform: 'translate(0, 0) scale(1)' },
                    '33%': { transform: 'translate(30px, -30px) scale(1.1)' },
                    '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
                },
                pulseDot: {
                    '0%, 100%': { opacity: '1', transform: 'scale(1)' },
                    '50%': { opacity: '0.4', transform: 'scale(1.3)' },
                },
                blink: {
                    '0%, 100%': { opacity: '1' },
                    '50%': { opacity: '0' },
                },
            },
        },
    },
    plugins: [],
}